### ISSUE TITLE
Dear Devolper - TCA Configuration Error

### ISSUE THREAD

**Issue by edekowalski** [t3kit/t3kit_extension_tools#2]
Dear Developer,

in the Backend at "Additional settings" > "Icon" I become this Error Message!

TCA Configuration error
PHP Runtime Deprecation Notice: Non-static method TYPO3\CMS\Core\Utility\File\BasicFileUtility::slashPath() should not be called statically, assuming $this from incompatible context in /var/www/html/typo3conf/ext/t3kit_extension_tools/Classes/UserFunction/IconFontSelector.php line 152

TYPO3 7.6.0 +  7.6.1
PHP 5.6.11 Zend Opcache v7.0.6-dev

Best Regards
Ede Kowalski

**Comment by pixelmatseriks** [comment]
Hi,

Thanks for your feedback.
I have replaced the slashPath call now, which is deprecated in TYPO3.

Regards
Mats

**Comment by edekowalski** [comment]
Dear Developer,

everything works fine!!

It is a realy cool package, an a nice Idea for beginner and advanced user
to test the new Features and Template technics with TYPO3.

I wish you and your Family a nice Christmas
Ede

:::Ede Kowalski
